"""Engine-agnostic streaming self-speculation for tool calls."""

from .controller import ForkController, ForkRunResult, ForkTrigger, first_output_trigger
from .decoding import (
    DecoderFactory,
    DeepSeekDsmlToolCallParser,
    DeepSeekV3ToolCallParser,
    JsonToolCallParser,
    ParserFactory,
    ParserRegistrationError,
    ParserRegistry,
    QwenXmlToolCallParser,
    PythonicToolCallParser,
    StreamingToolCallDecoder,
    TextToolCallParser,
    ToolCallDecoder,
    default_decoder,
    default_parser_registry,
)
from .engines import (
    CallableEngine,
    ChunkMapper,
    EngineCapabilityError,
    InferenceEngine,
    LlamaCppEngine,
    OpenAICompatibleEngine,
    OpenAIStreamError,
    SGLangEngine,
    StreamFactory,
    TGIEngine,
    VLLMEngine,
    default_chunk_mapper,
    validate_request,
)
from .forks import (
    CallableForkBuilder,
    ForkBuildError,
    ForkRequestBuilder,
    PrefixForkBuilder,
)
from .models import (
    EngineCapabilities,
    InferenceRequest,
    StreamChunk,
    StreamSnapshot,
    TokenLogprob,
    ToolCall,
    ToolCallDelta,
)
from .events import (
    ForkChunkEvent,
    ForkCompletedEvent,
    ForkEvent,
    ForkFailedEvent,
    ForkSkippedEvent,
    ForkStartedEvent,
    MainChunkEvent,
    MainCompletedEvent,
    ToolCallEvent,
)

__version__ = "0.1.0"

__all__ = [
    "EngineCapabilities",
    "EngineCapabilityError",
    "CallableEngine",
    "ChunkMapper",
    "DecoderFactory",
    "DeepSeekDsmlToolCallParser",
    "DeepSeekV3ToolCallParser",
    "CallableForkBuilder",
    "ForkBuildError",
    "ForkChunkEvent",
    "ForkCompletedEvent",
    "ForkController",
    "ForkEvent",
    "ForkFailedEvent",
    "ForkRequestBuilder",
    "ForkRunResult",
    "ForkSkippedEvent",
    "ForkStartedEvent",
    "ForkTrigger",
    "InferenceEngine",
    "InferenceRequest",
    "JsonToolCallParser",
    "LlamaCppEngine",
    "MainChunkEvent",
    "MainCompletedEvent",
    "OpenAICompatibleEngine",
    "OpenAIStreamError",
    "ParserFactory",
    "ParserRegistrationError",
    "ParserRegistry",
    "PrefixForkBuilder",
    "QwenXmlToolCallParser",
    "PythonicToolCallParser",
    "StreamChunk",
    "StreamFactory",
    "SGLangEngine",
    "StreamSnapshot",
    "StreamingToolCallDecoder",
    "TextToolCallParser",
    "TokenLogprob",
    "ToolCall",
    "ToolCallDecoder",
    "ToolCallDelta",
    "ToolCallEvent",
    "TGIEngine",
    "VLLMEngine",
    "__version__",
    "default_decoder",
    "default_chunk_mapper",
    "default_parser_registry",
    "first_output_trigger",
    "validate_request",
]
